### ISSUE TITLE
Change in-place functions to standard Julia syntax

### ISSUE THREAD

**Issue by matthewware** [BBN-Q/MESolve.jl#12]
Do people have strong opinions on updating the syntax from `dRho` to `dRho!` for in-place methods?

**Comment by luke-govia** [comment]
I'm fine with that. It seems reasonable to me. I wouldn't say it's high-priority though, since dRho is hidden from the user. That said, it's a pretty simple change to make if we're already modifying dRho.

**Comment by luke-govia** [comment]
Done in performance-tweaks
